name: Python CI/CD

# Trigger on push or pull request to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (optional)
      - name: Run tests
        run: |
          # If you have tests, e.g., pytest
          if [ -f "tests/test_app.py" ]; then
            pip install pytest
            pytest
          else
            echo "No tests found, skipping."
          fi

    # Step 5: Deploy (optional, example with Heroku)
    #- name: Deploy to Heroku
    #  uses: akhileshns/heroku-deploy@v3.12.12
    #  with:
    #    heroku_api_key: ${{secrets.HEROKU_API_KEY}}
    #    heroku_app_name: "your-heroku-app-name"
    #    heroku_email: "your-email@example.com"
